/*
 * Created by SharpDevelop.
 * User: vizir
 * Date: 2016-08-24
 * Time: 11:57
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Windows.Forms.DataVisualization.Charting;

namespace Registers
{
	/// <summary>
	/// Description of pepsinon.
	/// </summary>
	public partial class pepsinon : Form
	{
		public pepsinon()
		{
			//
			// The InitializeComponent() call is required for Windows Forms designer support.
			//
			InitializeComponent();
			
			//
			// TODO: Add constructor code after the InitializeComponent() call.
			//
//			Button1Click(null,null);
//			Button2Click(null,null);
//			Button6Click(null,null);
//			Button7Click(null,null);	
//			Button8Click(null,null);	
			dateTimePicker2.Format = DateTimePickerFormat.Custom;
			dateTimePicker2.CustomFormat = "yyyy.MM.dd";
			dateTimePicker1.Format = DateTimePickerFormat.Custom;
			dateTimePicker1.CustomFormat = "yyyy.MM.dd";			
		}
		void Button1Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegliqekw WHERE Datum = ('" + comboBox1.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart1.DataSource = ds.Tables[0];
			chart1.Titles.Add("Liquid non komformitások");
			chart1.Series.Add("Kimerve");
			chart1.Series["Kimerve"].YValueMembers = "Kimerve";
			chart1.Series["Kimerve"].XValueMember = "Datum";
			chart1.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart1.Series["Kimerve"].LegendText = "Kimérve";
			chart1.Series["Kimerve"].Color = Color.Red;
			chart1.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Felcimkezve");
			chart1.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart1.Series["Felcimkezve"].XValueMember = "Datum";
			chart1.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart1.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Uledeke");
			chart1.Series["Uledeke"].YValueMembers = "Uledeke";
			chart1.Series["Uledeke"].XValueMember = "Datum";
			chart1.Series["Uledeke"].ChartType = SeriesChartType.Column;
			chart1.Series["Uledeke"].LegendText = "Üledékes";
			chart1.Series["Uledeke"].Color = Color.Blue;
			chart1.Series["Uledeke"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Idegene");
			chart1.Series["Idegene"].YValueMembers = "Idegene";
			chart1.Series["Idegene"].XValueMember = "Datum";
			chart1.Series["Idegene"].ChartType = SeriesChartType.Column;
			chart1.Series["Idegene"].LegendText = "Idegen anyag";
			chart1.Series["Idegene"].Color = Color.Green;
			chart1.Series["Idegene"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Megfelelohoe");
			chart1.Series["Megfelelohoe"].YValueMembers = "Megfelelohoe";
			chart1.Series["Megfelelohoe"].XValueMember = "Datum";
			chart1.Series["Megfelelohoe"].ChartType = SeriesChartType.Column;							
			chart1.Series["Megfelelohoe"].Color = Color.Yellow;	
			chart1.Series["Megfelelohoe"].LegendText = "Megfelelő hő";
			chart1.Series["Series1"].IsVisibleInLegend = false;	
			chart1.Series["Megfelelohoe"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Komment");
			chart1.Series["Komment"].YValueMembers = "Megfelelohoe";
			chart1.Series["Komment"].XValueMember = "Datum";
			chart1.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart1.Series["Komment"].Color = Color.Black;	
			chart1.Series["Komment"].LegendText = "Kommentezés";
		}
		void Button2Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegaklekw WHERE Datum = ('" + comboBox1.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart2.DataSource = ds.Tables[0];
			chart2.Titles.Add("Akl non komformitások");
			chart2.Series.Add("Kimerve");
			chart2.Series["Kimerve"].YValueMembers = "Kimerve";
			chart2.Series["Kimerve"].XValueMember = "Datum";
			chart2.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart2.Series["Kimerve"].LegendText = "Kimérve";
			chart2.Series["Kimerve"].Color = Color.Red;
			chart2.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Csomomentes");
			chart2.Series["Csomomentes"].YValueMembers = "Csomomentes";
			chart2.Series["Csomomentes"].XValueMember = "Datum";
			chart2.Series["Csomomentes"].ChartType = SeriesChartType.Column;
			chart2.Series["Csomomentes"].LegendText = "Csomós";
			chart2.Series["Csomomentes"].Color = Color.Orange;
			chart2.Series["Csomomentes"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Felcimkezve");
			chart2.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart2.Series["Felcimkezve"].XValueMember = "Datum";
			chart2.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart2.Series["Felcimkezve"].Color = Color.Pink;
			chart2.Series["Felcimkezve"].LegendText = "Idegen anyag";
			chart2.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Komment");
			chart2.Series["Komment"].YValueMembers = "Komment";
			chart2.Series["Komment"].XValueMember = "Datum";
			chart2.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart2.Series["Komment"].Color = Color.Black;	
			chart2.Series["Komment"].LegendText = "Kommentezés";	
			chart2.Series["Series1"].IsVisibleInLegend = false;	
		}
		void Button6Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegbmpkw WHERE Datum = ('" + comboBox1.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart3.DataSource = ds.Tables[0];
			chart3.Titles.Add("Bmp non komformitások");
			chart3.Series.Add("IBCtisztae");
			chart3.Series["IBCtisztae"].YValueMembers = "IBCtisztae";
			chart3.Series["IBCtisztae"].XValueMember = "Datum";
			chart3.Series["IBCtisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["IBCtisztae"].LegendText = "IBC tiszta";
			chart3.Series["IBCtisztae"].Color = Color.Red;
			chart3.Series.Add("Allomastisztae");
			chart3.Series["Allomastisztae"].YValueMembers = "Allomastisztae";
			chart3.Series["Allomastisztae"].XValueMember = "Datum";
			chart3.Series["Allomastisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["Allomastisztae"].LegendText = "Állomás tiszta";
			chart3.Series["Allomastisztae"].Color = Color.Orange;
			chart3.Series.Add("Elese");
			chart3.Series["Elese"].YValueMembers = "Elese";
			chart3.Series["Elese"].XValueMember = "Datum";
			chart3.Series["Elese"].ChartType = SeriesChartType.Column;
			chart3.Series["Elese"].LegendText = "Kés élese";
			chart3.Series["Elese"].Color = Color.Purple;
			chart3.Series.Add("Kimerteke");
			chart3.Series["Kimerteke"].YValueMembers = "Kimerteke";
			chart3.Series["Kimerteke"].XValueMember = "Datum";
			chart3.Series["Kimerteke"].ChartType = SeriesChartType.Column;
			chart3.Series["Kimerteke"].LegendText = "Kimérés";
			chart3.Series["Kimerteke"].Color = Color.Blue;
			chart3.Series.Add("Csomomentese");
			chart3.Series["Csomomentese"].YValueMembers = "Csomomentese";
			chart3.Series["Csomomentese"].XValueMember = "Datum";
			chart3.Series["Csomomentese"].ChartType = SeriesChartType.Column;
			chart3.Series["Csomomentese"].LegendText = "Csomós";
			chart3.Series["Csomomentese"].Color = Color.Green;
			chart3.Series.Add("Alapanyage");
			chart3.Series["Alapanyage"].YValueMembers = "Alapanyage";
			chart3.Series["Alapanyage"].XValueMember = "Datum";
			chart3.Series["Alapanyage"].ChartType = SeriesChartType.Column;							
			chart3.Series["Alapanyage"].Color = Color.Yellow;	
			chart3.Series["Alapanyage"].LegendText = "Alapanyag csomagolás";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Bonthatoe");
			chart3.Series["Bonthatoe"].YValueMembers = "Bonthatoe";
			chart3.Series["Bonthatoe"].XValueMember = "Datum";
			chart3.Series["Bonthatoe"].ChartType = SeriesChartType.Column;							
			chart3.Series["Bonthatoe"].Color = Color.Brown;	
			chart3.Series["Bonthatoe"].LegendText = "Alapanyag bontható";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Idegene");
			chart3.Series["Idegene"].YValueMembers = "Idegene";
			chart3.Series["Idegene"].XValueMember = "Datum";
			chart3.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart3.Series["Idegene"].Color = Color.HotPink;	
			chart3.Series["Idegene"].LegendText = "Idegen anyag";
			chart3.Series.Add("Komment");
			chart3.Series["Komment"].YValueMembers = "Komment";
			chart3.Series["Komment"].XValueMember = "Datum";
			chart3.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart3.Series["Komment"].Color = Color.Black;	
			chart3.Series["Komment"].LegendText = "Kommentezés";
		}
		void Button7Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegblendekw WHERE Datum =  ('" + comboBox1.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart4.DataSource = ds.Tables[0];
			chart4.Titles.Add("Blend non komformitások");
			chart4.Series.Add("Tisztae");
			chart4.Series["Tisztae"].YValueMembers = "Tisztae";
			chart4.Series["Tisztae"].XValueMember = "Datum";
			chart4.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart4.Series["Tisztae"].LegendText = "Tisztaság";
			chart4.Series["Tisztae"].Color = Color.Red;
			chart4.Series.Add("Kitoltvee");
			chart4.Series["Kitoltvee"].YValueMembers = "Kitoltvee";
			chart4.Series["Kitoltvee"].XValueMember = "Datum";
			chart4.Series["Kitoltvee"].ChartType = SeriesChartType.Column;
			chart4.Series["Kitoltvee"].LegendText = "IBC kitöltés";
			chart4.Series["Kitoltvee"].Color = Color.Orange;
			chart4.Series.Add("IBCkiurulte");
			chart4.Series["IBCkiurulte"].YValueMembers = "IBCkiurulte";
			chart4.Series["IBCkiurulte"].XValueMember = "Datum";
			chart4.Series["IBCkiurulte"].ChartType = SeriesChartType.Column;
			chart4.Series["IBCkiurulte"].LegendText = "IBC kiürülés";
			chart4.Series["IBCkiurulte"].Color = Color.Purple;
			chart4.Series.Add("Felrazvae");
			chart4.Series["Felrazvae"].YValueMembers = "Felrazvae";
			chart4.Series["Felrazvae"].XValueMember = "Datum";
			chart4.Series["Felrazvae"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvae"].LegendText = "Felrázás";
			chart4.Series["Felrazvae"].Color = Color.Blue;
			chart4.Series.Add("Felrazvahoe");
			chart4.Series["Felrazvahoe"].YValueMembers = "Felrazvahoe";
			chart4.Series["Felrazvahoe"].XValueMember = "Datum";
			chart4.Series["Felrazvahoe"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvahoe"].LegendText = "Folyadék hőmérséklet";
			chart4.Series["Felrazvahoe"].Color = Color.Green;
			chart4.Series.Add("Jerrycane");
			chart4.Series["Jerrycane"].YValueMembers = "Jerrycane";
			chart4.Series["Jerrycane"].XValueMember = "Datum";
			chart4.Series["Jerrycane"].ChartType = SeriesChartType.Column;							
			chart4.Series["Jerrycane"].Color = Color.Yellow;	
			chart4.Series["Jerrycane"].LegendText = "Jerrycane";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Urese");
			chart4.Series["Urese"].YValueMembers = "Urese";
			chart4.Series["Urese"].XValueMember = "Datum";
			chart4.Series["Urese"].ChartType = SeriesChartType.Column;							
			chart4.Series["Urese"].Color = Color.Brown;	
			chart4.Series["Urese"].LegendText = "Liquid tank üres";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Automatae");
			chart4.Series["Automatae"].YValueMembers = "Automatae";
			chart4.Series["Automatae"].XValueMember = "Datum";
			chart4.Series["Automatae"].ChartType = SeriesChartType.Column;							
			chart4.Series["Automatae"].Color = Color.RosyBrown;	
			chart4.Series["Automatae"].LegendText = "Automata hiba";			
			chart4.Series.Add("Szivarogepor");
			chart4.Series["Szivarogepor"].YValueMembers = "Szivarogepor";
			chart4.Series["Szivarogepor"].XValueMember = "Datum";
			chart4.Series["Szivarogepor"].ChartType = SeriesChartType.Column;
			chart4.Series["Szivarogepor"].LegendText = "Porszivárgás";
			chart4.Series["Szivarogepor"].Color = Color.DarkRed;
			chart4.Series.Add("Szivaroge");
			chart4.Series["Szivaroge"].YValueMembers = "Szivaroge";
			chart4.Series["Szivaroge"].XValueMember = "Datum";
			chart4.Series["Szivaroge"].ChartType = SeriesChartType.Column;							
			chart4.Series["Szivaroge"].Color = Color.DarkOliveGreen;	
			chart4.Series["Szivaroge"].LegendText = "Szivárgás";	
			chart4.Series.Add("Muszakie");
			chart4.Series["Muszakie"].YValueMembers = "Muszakie";
			chart4.Series["Muszakie"].XValueMember = "Datum";
			chart4.Series["Muszakie"].ChartType = SeriesChartType.Column;							
			chart4.Series["Muszakie"].Color = Color.Brown;	
			chart4.Series["Muszakie"].LegendText = "Műszaki hiba";	
			chart4.Series.Add("Idegene");
			chart4.Series["Idegene"].YValueMembers = "Idegene";
			chart4.Series["Idegene"].XValueMember = "Datum";
			chart4.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart4.Series["Idegene"].Color = Color.HotPink;	
			chart4.Series["Idegene"].LegendText = "Idegen anyag";			
			chart4.Series.Add("Komment");
			chart4.Series["Komment"].YValueMembers = "Komment";
			chart4.Series["Komment"].XValueMember = "Datum";
			chart4.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart4.Series["Komment"].Color = Color.Black;	
			chart4.Series["Komment"].LegendText = "Kommentezés";	
		}
		void Button8Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select * FROM nemmegpackekw WHERE Datum = ('" + comboBox1.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart5.DataSource = ds.Tables[0];
			chart5.Titles.Add("Pack non komformitások");
			chart5.Series.Add("Tisztae");
			chart5.Series["Tisztae"].YValueMembers = "Tisztae";
			chart5.Series["Tisztae"].XValueMember = "Datum";
			chart5.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Tisztae"].LegendText = "Tisztaság";
			chart5.Series["Tisztae"].Color = Color.Red;
			chart5.Series.Add("POStisztae");
			chart5.Series["POStisztae"].YValueMembers = "POStisztae";
			chart5.Series["POStisztae"].XValueMember = "Datum";
			chart5.Series["POStisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["POStisztae"].LegendText = "POS tiszta";
			chart5.Series["POStisztae"].Color = Color.Orange;
			chart5.Series.Add("Kezitisztae");
			chart5.Series["Kezitisztae"].YValueMembers = "Kezitisztae";
			chart5.Series["Kezitisztae"].XValueMember = "Datum";
			chart5.Series["Kezitisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Kezitisztae"].LegendText = "Kézi tisztítás";
			chart5.Series["Kezitisztae"].Color = Color.Purple;
			chart5.Series.Add("Prepordere");
			chart5.Series["Prepordere"].YValueMembers = "Prepordere";
			chart5.Series["Prepordere"].XValueMember = "Datum";
			chart5.Series["Prepordere"].ChartType = SeriesChartType.Column;
			chart5.Series["Prepordere"].LegendText = "Preporder";
			chart5.Series["Prepordere"].Color = Color.Blue;
			chart5.Series.Add("Szitae");
			chart5.Series["Szitae"].YValueMembers = "Szitae";
			chart5.Series["Szitae"].XValueMember = "Datum";
			chart5.Series["Szitae"].ChartType = SeriesChartType.Column;
			chart5.Series["Szitae"].LegendText = "Szita";
			chart5.Series["Szitae"].Color = Color.Green;
			chart5.Series.Add("Szitaellazone");
			chart5.Series["Szitaellazone"].YValueMembers = "Szitaellazone";
			chart5.Series["Szitaellazone"].XValueMember = "Datum";
			chart5.Series["Szitaellazone"].ChartType = SeriesChartType.Column;							
			chart5.Series["Szitaellazone"].Color = Color.Yellow;	
			chart5.Series["Szitaellazone"].LegendText = "Szita azonos anyag";
			chart5.Series["Series1"].IsVisibleInLegend = false;	
			chart5.Series.Add("Serulese");
			chart5.Series["Serulese"].YValueMembers = "Serulese";
			chart5.Series["Serulese"].XValueMember = "Datum";
			chart5.Series["Serulese"].ChartType = SeriesChartType.Column;							
			chart5.Series["Serulese"].Color = Color.Brown;	
			chart5.Series["Serulese"].LegendText = "Bélészsák sérülés";	
			chart5.Series.Add("Beleszsake");
			chart5.Series["Beleszsake"].YValueMembers = "Beleszsake";
			chart5.Series["Beleszsake"].XValueMember = "Datum";
			chart5.Series["Beleszsake"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsake"].Color = Color.RosyBrown;	
			chart5.Series["Beleszsake"].LegendText = "Bélészsák tiszta";			
			chart5.Series.Add("Szinhomogene");
			chart5.Series["Szinhomogene"].YValueMembers = "Szinhomogene";
			chart5.Series["Szinhomogene"].XValueMember = "Datum";
			chart5.Series["Szinhomogene"].ChartType = SeriesChartType.Column;
			chart5.Series["Szinhomogene"].LegendText = "Homogén szín";
			chart5.Series["Szinhomogene"].Color = Color.DarkRed;
			chart5.Series.Add("Beleszsakzare");
			chart5.Series["Beleszsakzare"].YValueMembers = "Beleszsakzare";
			chart5.Series["Beleszsakzare"].XValueMember = "Datum";
			chart5.Series["Beleszsakzare"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsakzare"].Color = Color.DarkOliveGreen;	
			chart5.Series["Beleszsakzare"].LegendText = "Bélészsák zár";	
			chart5.Series.Add("Packofffolye");
			chart5.Series["Packofffolye"].YValueMembers = "Packofffolye";
			chart5.Series["Packofffolye"].XValueMember = "Datum";
			chart5.Series["Packofffolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Packofffolye"].Color = Color.DarkSeaGreen;	
			chart5.Series["Packofffolye"].LegendText = "Pack off assign";	
			chart5.Series.Add("Idegene");
			chart5.Series["Idegene"].YValueMembers = "Idegene";
			chart5.Series["Idegene"].XValueMember = "Datum";
			chart5.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart5.Series["Idegene"].Color = Color.HotPink;	
			chart5.Series["Idegene"].LegendText = "Idegen anyag";	
			chart5.Series.Add("Vizfolye");
			chart5.Series["Vizfolye"].YValueMembers = "Vizfolye";
			chart5.Series["Vizfolye"].XValueMember = "Datum";
			chart5.Series["Vizfolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Vizfolye"].Color = Color.LimeGreen;	
			chart5.Series["Vizfolye"].LegendText = "Vízfolyás";			
			chart5.Series.Add("Komment");
			chart5.Series["Komment"].YValueMembers = "Komment";
			chart5.Series["Komment"].XValueMember = "Datum";
			chart5.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart5.Series["Komment"].Color = Color.Black;	
			chart5.Series["Komment"].LegendText = "Kommentezés";
		}
		void Button10Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegliqekm WHERE Datum = ('" + comboBox3.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart1.DataSource = ds.Tables[0];
			chart1.Titles.Add("Liquid non komformitások");
			chart1.Series.Add("Kimerve");
			chart1.Series["Kimerve"].YValueMembers = "Kimerve";
			chart1.Series["Kimerve"].XValueMember = "Datum";
			chart1.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart1.Series["Kimerve"].LegendText = "Kimérve";
			chart1.Series["Kimerve"].Color = Color.Red;
			chart1.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Felcimkezve");
			chart1.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart1.Series["Felcimkezve"].XValueMember = "Datum";
			chart1.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart1.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Uledeke");
			chart1.Series["Uledeke"].YValueMembers = "Uledeke";
			chart1.Series["Uledeke"].XValueMember = "Datum";
			chart1.Series["Uledeke"].ChartType = SeriesChartType.Column;
			chart1.Series["Uledeke"].LegendText = "Üledékes";
			chart1.Series["Uledeke"].Color = Color.Blue;
			chart1.Series["Uledeke"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Idegene");
			chart1.Series["Idegene"].YValueMembers = "Idegene";
			chart1.Series["Idegene"].XValueMember = "Datum";
			chart1.Series["Idegene"].ChartType = SeriesChartType.Column;
			chart1.Series["Idegene"].LegendText = "Idegen anyag";
			chart1.Series["Idegene"].Color = Color.Green;
			chart1.Series["Idegene"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Megfelelohoe");
			chart1.Series["Megfelelohoe"].YValueMembers = "Megfelelohoe";
			chart1.Series["Megfelelohoe"].XValueMember = "Datum";
			chart1.Series["Megfelelohoe"].ChartType = SeriesChartType.Column;							
			chart1.Series["Megfelelohoe"].Color = Color.Yellow;	
			chart1.Series["Megfelelohoe"].LegendText = "Megfelelő hő";
			chart1.Series["Series1"].IsVisibleInLegend = false;	
			chart1.Series["Megfelelohoe"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Komment");
			chart1.Series["Komment"].YValueMembers = "Megfelelohoe";
			chart1.Series["Komment"].XValueMember = "Datum";
			chart1.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart1.Series["Komment"].Color = Color.Black;	
			chart1.Series["Komment"].LegendText = "Kommentezés";	
		}
		void Button11Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegaklekm WHERE Datum = ('" + comboBox3.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart2.DataSource = ds.Tables[0];
			chart2.Titles.Add("Akl non komformitások");
			chart2.Series.Add("Kimerve");
			chart2.Series["Kimerve"].YValueMembers = "Kimerve";
			chart2.Series["Kimerve"].XValueMember = "Datum";
			chart2.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart2.Series["Kimerve"].LegendText = "Kimérve";
			chart2.Series["Kimerve"].Color = Color.Red;
			chart2.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Csomomentes");
			chart2.Series["Csomomentes"].YValueMembers = "Csomomentes";
			chart2.Series["Csomomentes"].XValueMember = "Datum";
			chart2.Series["Csomomentes"].ChartType = SeriesChartType.Column;
			chart2.Series["Csomomentes"].LegendText = "Csomós";
			chart2.Series["Csomomentes"].Color = Color.Orange;
			chart2.Series["Csomomentes"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Felcimkezve");
			chart2.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart2.Series["Felcimkezve"].XValueMember = "Datum";
			chart2.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart2.Series["Felcimkezve"].Color = Color.Pink;
			chart2.Series["Felcimkezve"].LegendText = "Idegen anyag";
			chart2.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Komment");
			chart2.Series["Komment"].YValueMembers = "Komment";
			chart2.Series["Komment"].XValueMember = "Datum";
			chart2.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart2.Series["Komment"].Color = Color.Black;	
			chart2.Series["Komment"].LegendText = "Kommentezés";	
			chart2.Series["Series1"].IsVisibleInLegend = false;		
		}
		void Button12Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegbmpkm WHERE Datum = ('" + comboBox3.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart3.DataSource = ds.Tables[0];
			chart3.Titles.Add("Bmp non komformitások");
			chart3.Series.Add("IBCtisztae");
			chart3.Series["IBCtisztae"].YValueMembers = "IBCtisztae";
			chart3.Series["IBCtisztae"].XValueMember = "Datum";
			chart3.Series["IBCtisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["IBCtisztae"].LegendText = "IBC tiszta";
			chart3.Series["IBCtisztae"].Color = Color.Red;
			chart3.Series.Add("Allomastisztae");
			chart3.Series["Allomastisztae"].YValueMembers = "Allomastisztae";
			chart3.Series["Allomastisztae"].XValueMember = "Datum";
			chart3.Series["Allomastisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["Allomastisztae"].LegendText = "Állomás tiszta";
			chart3.Series["Allomastisztae"].Color = Color.Orange;
			chart3.Series.Add("Elese");
			chart3.Series["Elese"].YValueMembers = "Elese";
			chart3.Series["Elese"].XValueMember = "Datum";
			chart3.Series["Elese"].ChartType = SeriesChartType.Column;
			chart3.Series["Elese"].LegendText = "Kés élese";
			chart3.Series["Elese"].Color = Color.Purple;
			chart3.Series.Add("Kimerteke");
			chart3.Series["Kimerteke"].YValueMembers = "Kimerteke";
			chart3.Series["Kimerteke"].XValueMember = "Datum";
			chart3.Series["Kimerteke"].ChartType = SeriesChartType.Column;
			chart3.Series["Kimerteke"].LegendText = "Kimérés";
			chart3.Series["Kimerteke"].Color = Color.Blue;
			chart3.Series.Add("Csomomentese");
			chart3.Series["Csomomentese"].YValueMembers = "Csomomentese";
			chart3.Series["Csomomentese"].XValueMember = "Datum";
			chart3.Series["Csomomentese"].ChartType = SeriesChartType.Column;
			chart3.Series["Csomomentese"].LegendText = "Csomós";
			chart3.Series["Csomomentese"].Color = Color.Green;
			chart3.Series.Add("Alapanyage");
			chart3.Series["Alapanyage"].YValueMembers = "Alapanyage";
			chart3.Series["Alapanyage"].XValueMember = "Datum";
			chart3.Series["Alapanyage"].ChartType = SeriesChartType.Column;							
			chart3.Series["Alapanyage"].Color = Color.Yellow;	
			chart3.Series["Alapanyage"].LegendText = "Alapanyag csomagolás";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Bonthatoe");
			chart3.Series["Bonthatoe"].YValueMembers = "Bonthatoe";
			chart3.Series["Bonthatoe"].XValueMember = "Datum";
			chart3.Series["Bonthatoe"].ChartType = SeriesChartType.Column;							
			chart3.Series["Bonthatoe"].Color = Color.Brown;	
			chart3.Series["Bonthatoe"].LegendText = "Alapanyag bontható";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Idegene");
			chart3.Series["Idegene"].YValueMembers = "Idegene";
			chart3.Series["Idegene"].XValueMember = "Datum";
			chart3.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart3.Series["Idegene"].Color = Color.HotPink;	
			chart3.Series["Idegene"].LegendText = "Idegen anyag";
			chart3.Series.Add("Komment");
			chart3.Series["Komment"].YValueMembers = "Komment";
			chart3.Series["Komment"].XValueMember = "Datum";
			chart3.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart3.Series["Komment"].Color = Color.Black;	
			chart3.Series["Komment"].LegendText = "Kommentezés";	
		}
		void Button13Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegblendekm WHERE Datum =  ('" + comboBox3.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart4.DataSource = ds.Tables[0];
			chart4.Titles.Add("Blend non komformitások");
			chart4.Series.Add("Tisztae");
			chart4.Series["Tisztae"].YValueMembers = "Tisztae";
			chart4.Series["Tisztae"].XValueMember = "Datum";
			chart4.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart4.Series["Tisztae"].LegendText = "Tisztaság";
			chart4.Series["Tisztae"].Color = Color.Red;
			chart4.Series.Add("Kitoltvee");
			chart4.Series["Kitoltvee"].YValueMembers = "Kitoltvee";
			chart4.Series["Kitoltvee"].XValueMember = "Datum";
			chart4.Series["Kitoltvee"].ChartType = SeriesChartType.Column;
			chart4.Series["Kitoltvee"].LegendText = "IBC kitöltés";
			chart4.Series["Kitoltvee"].Color = Color.Orange;
			chart4.Series.Add("IBCkiurulte");
			chart4.Series["IBCkiurulte"].YValueMembers = "IBCkiurulte";
			chart4.Series["IBCkiurulte"].XValueMember = "Datum";
			chart4.Series["IBCkiurulte"].ChartType = SeriesChartType.Column;
			chart4.Series["IBCkiurulte"].LegendText = "IBC kiürülés";
			chart4.Series["IBCkiurulte"].Color = Color.Purple;
			chart4.Series.Add("Felrazvae");
			chart4.Series["Felrazvae"].YValueMembers = "Felrazvae";
			chart4.Series["Felrazvae"].XValueMember = "Datum";
			chart4.Series["Felrazvae"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvae"].LegendText = "Felrázás";
			chart4.Series["Felrazvae"].Color = Color.Blue;
			chart4.Series.Add("Felrazvahoe");
			chart4.Series["Felrazvahoe"].YValueMembers = "Felrazvahoe";
			chart4.Series["Felrazvahoe"].XValueMember = "Datum";
			chart4.Series["Felrazvahoe"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvahoe"].LegendText = "Folyadék hőmérséklet";
			chart4.Series["Felrazvahoe"].Color = Color.Green;
			chart4.Series.Add("Jerrycane");
			chart4.Series["Jerrycane"].YValueMembers = "Jerrycane";
			chart4.Series["Jerrycane"].XValueMember = "Datum";
			chart4.Series["Jerrycane"].ChartType = SeriesChartType.Column;							
			chart4.Series["Jerrycane"].Color = Color.Yellow;	
			chart4.Series["Jerrycane"].LegendText = "Jerrycane";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Urese");
			chart4.Series["Urese"].YValueMembers = "Urese";
			chart4.Series["Urese"].XValueMember = "Datum";
			chart4.Series["Urese"].ChartType = SeriesChartType.Column;							
			chart4.Series["Urese"].Color = Color.Brown;	
			chart4.Series["Urese"].LegendText = "Liquid tank üres";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Automatae");
			chart4.Series["Automatae"].YValueMembers = "Automatae";
			chart4.Series["Automatae"].XValueMember = "Datum";
			chart4.Series["Automatae"].ChartType = SeriesChartType.Column;							
			chart4.Series["Automatae"].Color = Color.RosyBrown;	
			chart4.Series["Automatae"].LegendText = "Automata hiba";			
			chart4.Series.Add("Szivarogepor");
			chart4.Series["Szivarogepor"].YValueMembers = "Szivarogepor";
			chart4.Series["Szivarogepor"].XValueMember = "Datum";
			chart4.Series["Szivarogepor"].ChartType = SeriesChartType.Column;
			chart4.Series["Szivarogepor"].LegendText = "Porszivárgás";
			chart4.Series["Szivarogepor"].Color = Color.DarkRed;
			chart4.Series.Add("Szivaroge");
			chart4.Series["Szivaroge"].YValueMembers = "Szivaroge";
			chart4.Series["Szivaroge"].XValueMember = "Datum";
			chart4.Series["Szivaroge"].ChartType = SeriesChartType.Column;							
			chart4.Series["Szivaroge"].Color = Color.DarkOliveGreen;	
			chart4.Series["Szivaroge"].LegendText = "Szivárgás";	
			chart4.Series.Add("Muszakie");
			chart4.Series["Muszakie"].YValueMembers = "Muszakie";
			chart4.Series["Muszakie"].XValueMember = "Datum";
			chart4.Series["Muszakie"].ChartType = SeriesChartType.Column;							
			chart4.Series["Muszakie"].Color = Color.Brown;	
			chart4.Series["Muszakie"].LegendText = "Műszaki hiba";	
			chart4.Series.Add("Idegene");
			chart4.Series["Idegene"].YValueMembers = "Idegene";
			chart4.Series["Idegene"].XValueMember = "Datum";
			chart4.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart4.Series["Idegene"].Color = Color.HotPink;	
			chart4.Series["Idegene"].LegendText = "Idegen anyag";			
			chart4.Series.Add("Komment");
			chart4.Series["Komment"].YValueMembers = "Komment";
			chart4.Series["Komment"].XValueMember = "Datum";
			chart4.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart4.Series["Komment"].Color = Color.Black;	
			chart4.Series["Komment"].LegendText = "Kommentezés";		
		}
		void Button14Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select * FROM nemmegpackekm WHERE Datum = ('" + comboBox3.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart5.DataSource = ds.Tables[0];
			chart5.Titles.Add("Pack non komformitások");
			chart5.Series.Add("Tisztae");
			chart5.Series["Tisztae"].YValueMembers = "Tisztae";
			chart5.Series["Tisztae"].XValueMember = "Datum";
			chart5.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Tisztae"].LegendText = "Tisztaság";
			chart5.Series["Tisztae"].Color = Color.Red;
			chart5.Series.Add("POStisztae");
			chart5.Series["POStisztae"].YValueMembers = "POStisztae";
			chart5.Series["POStisztae"].XValueMember = "Datum";
			chart5.Series["POStisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["POStisztae"].LegendText = "POS tiszta";
			chart5.Series["POStisztae"].Color = Color.Orange;
			chart5.Series.Add("Kezitisztae");
			chart5.Series["Kezitisztae"].YValueMembers = "Kezitisztae";
			chart5.Series["Kezitisztae"].XValueMember = "Datum";
			chart5.Series["Kezitisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Kezitisztae"].LegendText = "Kézi tisztítás";
			chart5.Series["Kezitisztae"].Color = Color.Purple;
			chart5.Series.Add("Prepordere");
			chart5.Series["Prepordere"].YValueMembers = "Prepordere";
			chart5.Series["Prepordere"].XValueMember = "Datum";
			chart5.Series["Prepordere"].ChartType = SeriesChartType.Column;
			chart5.Series["Prepordere"].LegendText = "Preporder";
			chart5.Series["Prepordere"].Color = Color.Blue;
			chart5.Series.Add("Szitae");
			chart5.Series["Szitae"].YValueMembers = "Szitae";
			chart5.Series["Szitae"].XValueMember = "Datum";
			chart5.Series["Szitae"].ChartType = SeriesChartType.Column;
			chart5.Series["Szitae"].LegendText = "Szita";
			chart5.Series["Szitae"].Color = Color.Green;
			chart5.Series.Add("Szitaellazone");
			chart5.Series["Szitaellazone"].YValueMembers = "Szitaellazone";
			chart5.Series["Szitaellazone"].XValueMember = "Datum";
			chart5.Series["Szitaellazone"].ChartType = SeriesChartType.Column;							
			chart5.Series["Szitaellazone"].Color = Color.Yellow;	
			chart5.Series["Szitaellazone"].LegendText = "Szita azonos anyag";
			chart5.Series["Series1"].IsVisibleInLegend = false;	
			chart5.Series.Add("Serulese");
			chart5.Series["Serulese"].YValueMembers = "Serulese";
			chart5.Series["Serulese"].XValueMember = "Datum";
			chart5.Series["Serulese"].ChartType = SeriesChartType.Column;							
			chart5.Series["Serulese"].Color = Color.SaddleBrown;	
			chart5.Series["Serulese"].LegendText = "Bélészsák sérülés";	
			chart5.Series.Add("Beleszsake");
			chart5.Series["Beleszsake"].YValueMembers = "Beleszsake";
			chart5.Series["Beleszsake"].XValueMember = "Datum";
			chart5.Series["Beleszsake"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsake"].Color = Color.PaleGoldenrod;	
			chart5.Series["Beleszsake"].LegendText = "Bélészsák tiszta";			
			chart5.Series.Add("Szinhomogene");
			chart5.Series["Szinhomogene"].YValueMembers = "Szinhomogene";
			chart5.Series["Szinhomogene"].XValueMember = "Datum";
			chart5.Series["Szinhomogene"].ChartType = SeriesChartType.Column;
			chart5.Series["Szinhomogene"].LegendText = "Homogén szín";
			chart5.Series["Szinhomogene"].Color = Color.DarkRed;
			chart5.Series.Add("Beleszsakzare");
			chart5.Series["Beleszsakzare"].YValueMembers = "Beleszsakzare";
			chart5.Series["Beleszsakzare"].XValueMember = "Datum";
			chart5.Series["Beleszsakzare"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsakzare"].Color = Color.DarkOliveGreen;	
			chart5.Series["Beleszsakzare"].LegendText = "Bélészsák zár";	
			chart5.Series.Add("Packofffolye");
			chart5.Series["Packofffolye"].YValueMembers = "Packofffolye";
			chart5.Series["Packofffolye"].XValueMember = "Datum";
			chart5.Series["Packofffolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Packofffolye"].Color = Color.DarkSeaGreen;	
			chart5.Series["Packofffolye"].LegendText = "Pack off assign";	
			chart5.Series.Add("Idegene");
			chart5.Series["Idegene"].YValueMembers = "Idegene";
			chart5.Series["Idegene"].XValueMember = "Datum";
			chart5.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart5.Series["Idegene"].Color = Color.HotPink;	
			chart5.Series["Idegene"].LegendText = "Idegen anyag";	
			chart5.Series.Add("Vizfolye");
			chart5.Series["Vizfolye"].YValueMembers = "Vizfolye";
			chart5.Series["Vizfolye"].XValueMember = "Datum";
			chart5.Series["Vizfolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Vizfolye"].Color = Color.LimeGreen;	
			chart5.Series["Vizfolye"].LegendText = "Vízfolyás";			
			chart5.Series.Add("Komment");
			chart5.Series["Komment"].YValueMembers = "Komment";
			chart5.Series["Komment"].XValueMember = "Datum";
			chart5.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart5.Series["Komment"].Color = Color.Black;	
			chart5.Series["Komment"].LegendText = "Kommentezés";	
		}
		void ComboBox2SelectedIndexChanged(object sender, EventArgs e)
		{
			Button1Click(null,null);
			Button2Click(null,null);
			Button6Click(null,null);
			Button7Click(null,null);	
			Button8Click(null,null);
			comboBox3.Enabled = false;
			comboBox1.Enabled = false;
			comboBox2.Enabled = false;		
			dateTimePicker2.Enabled = false;
		}
		void ComboBox3SelectedIndexChanged(object sender, EventArgs e)
		{
			Button10Click(null,null);
			Button11Click(null,null);
			Button12Click(null,null);
			Button13Click(null,null);	
			Button14Click(null,null);
			comboBox3.Enabled = false;
			comboBox1.Enabled = false;
			comboBox2.Enabled = false;		
			dateTimePicker2.Enabled = false;
		}
		void ComboBox1SelectedIndexChanged(object sender, EventArgs e)
		{
			Button9Click(null,null);
			Button15Click(null,null);
			Button16Click(null,null);
			Button17Click(null,null);	
			Button18Click(null,null);
			comboBox3.Enabled = false;
			comboBox1.Enabled = false;
			comboBox2.Enabled = false;		
			dateTimePicker2.Enabled = false;
		}
		void Button9Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegliqeky WHERE Datum = ('" + comboBox2.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart1.DataSource = ds.Tables[0];
			chart1.Titles.Add("Liquid non komformitások");
			chart1.Series.Add("Kimerve");
			chart1.Series["Kimerve"].YValueMembers = "Kimerve";
			chart1.Series["Kimerve"].XValueMember = "Datum";
			chart1.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart1.Series["Kimerve"].LegendText = "Kimérve";
			chart1.Series["Kimerve"].Color = Color.Red;
			chart1.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Felcimkezve");
			chart1.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart1.Series["Felcimkezve"].XValueMember = "Datum";
			chart1.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart1.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Uledeke");
			chart1.Series["Uledeke"].YValueMembers = "Uledeke";
			chart1.Series["Uledeke"].XValueMember = "Datum";
			chart1.Series["Uledeke"].ChartType = SeriesChartType.Column;
			chart1.Series["Uledeke"].LegendText = "Üledékes";
			chart1.Series["Uledeke"].Color = Color.Blue;
			chart1.Series["Uledeke"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Idegene");
			chart1.Series["Idegene"].YValueMembers = "Idegene";
			chart1.Series["Idegene"].XValueMember = "Datum";
			chart1.Series["Idegene"].ChartType = SeriesChartType.Column;
			chart1.Series["Idegene"].LegendText = "Idegen anyag";
			chart1.Series["Idegene"].Color = Color.Green;
			chart1.Series["Idegene"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Megfelelohoe");
			chart1.Series["Megfelelohoe"].YValueMembers = "Megfelelohoe";
			chart1.Series["Megfelelohoe"].XValueMember = "Datum";
			chart1.Series["Megfelelohoe"].ChartType = SeriesChartType.Column;							
			chart1.Series["Megfelelohoe"].Color = Color.Yellow;	
			chart1.Series["Megfelelohoe"].LegendText = "Megfelelő hő";
			chart1.Series["Series1"].IsVisibleInLegend = false;	
			chart1.Series["Megfelelohoe"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Komment");
			chart1.Series["Komment"].YValueMembers = "Megfelelohoe";
			chart1.Series["Komment"].XValueMember = "Datum";
			chart1.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart1.Series["Komment"].Color = Color.Black;	
			chart1.Series["Komment"].LegendText = "Kommentezés";	
		}
		void Button15Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegakleky WHERE Datum = ('" + comboBox2.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart2.DataSource = ds.Tables[0];
			chart2.Titles.Add("Akl non komformitások");
			chart2.Series.Add("Kimerve");
			chart2.Series["Kimerve"].YValueMembers = "Kimerve";
			chart2.Series["Kimerve"].XValueMember = "Datum";
			chart2.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart2.Series["Kimerve"].LegendText = "Kimérve";
			chart2.Series["Kimerve"].Color = Color.Red;
			chart2.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Csomomentes");
			chart2.Series["Csomomentes"].YValueMembers = "Csomomentes";
			chart2.Series["Csomomentes"].XValueMember = "Datum";
			chart2.Series["Csomomentes"].ChartType = SeriesChartType.Column;
			chart2.Series["Csomomentes"].LegendText = "Csomós";
			chart2.Series["Csomomentes"].Color = Color.Orange;
			chart2.Series["Csomomentes"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Felcimkezve");
			chart2.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart2.Series["Felcimkezve"].XValueMember = "Datum";
			chart2.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart2.Series["Felcimkezve"].Color = Color.Pink;
			chart2.Series["Felcimkezve"].LegendText = "Idegen anyag";
			chart2.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Komment");
			chart2.Series["Komment"].YValueMembers = "Komment";
			chart2.Series["Komment"].XValueMember = "Datum";
			chart2.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart2.Series["Komment"].Color = Color.Black;	
			chart2.Series["Komment"].LegendText = "Kommentezés";	
			chart2.Series["Series1"].IsVisibleInLegend = false;		
		}
		void Button16Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegbmpky WHERE Datum = ('" + comboBox2.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart3.DataSource = ds.Tables[0];
			chart3.Titles.Add("Bmp non komformitások");
			chart3.Series.Add("IBCtisztae");
			chart3.Series["IBCtisztae"].YValueMembers = "IBCtisztae";
			chart3.Series["IBCtisztae"].XValueMember = "Datum";
			chart3.Series["IBCtisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["IBCtisztae"].LegendText = "IBC tiszta";
			chart3.Series["IBCtisztae"].Color = Color.Red;
			chart3.Series.Add("Allomastisztae");
			chart3.Series["Allomastisztae"].YValueMembers = "Allomastisztae";
			chart3.Series["Allomastisztae"].XValueMember = "Datum";
			chart3.Series["Allomastisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["Allomastisztae"].LegendText = "Állomás tiszta";
			chart3.Series["Allomastisztae"].Color = Color.Orange;
			chart3.Series.Add("Elese");
			chart3.Series["Elese"].YValueMembers = "Elese";
			chart3.Series["Elese"].XValueMember = "Datum";
			chart3.Series["Elese"].ChartType = SeriesChartType.Column;
			chart3.Series["Elese"].LegendText = "Kés élese";
			chart3.Series["Elese"].Color = Color.Purple;
			chart3.Series.Add("Kimerteke");
			chart3.Series["Kimerteke"].YValueMembers = "Kimerteke";
			chart3.Series["Kimerteke"].XValueMember = "Datum";
			chart3.Series["Kimerteke"].ChartType = SeriesChartType.Column;
			chart3.Series["Kimerteke"].LegendText = "Kimérés";
			chart3.Series["Kimerteke"].Color = Color.Blue;
			chart3.Series.Add("Csomomentese");
			chart3.Series["Csomomentese"].YValueMembers = "Csomomentese";
			chart3.Series["Csomomentese"].XValueMember = "Datum";
			chart3.Series["Csomomentese"].ChartType = SeriesChartType.Column;
			chart3.Series["Csomomentese"].LegendText = "Csomós";
			chart3.Series["Csomomentese"].Color = Color.Green;
			chart3.Series.Add("Alapanyage");
			chart3.Series["Alapanyage"].YValueMembers = "Alapanyage";
			chart3.Series["Alapanyage"].XValueMember = "Datum";
			chart3.Series["Alapanyage"].ChartType = SeriesChartType.Column;							
			chart3.Series["Alapanyage"].Color = Color.Yellow;	
			chart3.Series["Alapanyage"].LegendText = "Alapanyag csomagolás";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Bonthatoe");
			chart3.Series["Bonthatoe"].YValueMembers = "Bonthatoe";
			chart3.Series["Bonthatoe"].XValueMember = "Datum";
			chart3.Series["Bonthatoe"].ChartType = SeriesChartType.Column;							
			chart3.Series["Bonthatoe"].Color = Color.Brown;	
			chart3.Series["Bonthatoe"].LegendText = "Alapanyag bontható";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Idegene");
			chart3.Series["Idegene"].YValueMembers = "Idegene";
			chart3.Series["Idegene"].XValueMember = "Datum";
			chart3.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart3.Series["Idegene"].Color = Color.HotPink;	
			chart3.Series["Idegene"].LegendText = "Idegen anyag";
			chart3.Series.Add("Komment");
			chart3.Series["Komment"].YValueMembers = "Komment";
			chart3.Series["Komment"].XValueMember = "Datum";
			chart3.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart3.Series["Komment"].Color = Color.Black;	
			chart3.Series["Komment"].LegendText = "Kommentezés";	
	
		}
		void Button17Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("SELECT * FROM nemmegblendeky WHERE Datum =  ('" + comboBox2.Text +"') ORDER BY Datum", conn);
			dataAdapter1.Fill(ds);	
			chart4.DataSource = ds.Tables[0];
			chart4.Titles.Add("Blend non komformitások");
			chart4.Series.Add("Tisztae");
			chart4.Series["Tisztae"].YValueMembers = "Tisztae";
			chart4.Series["Tisztae"].XValueMember = "Datum";
			chart4.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart4.Series["Tisztae"].LegendText = "Tisztaság";
			chart4.Series["Tisztae"].Color = Color.Red;
			chart4.Series.Add("Kitoltvee");
			chart4.Series["Kitoltvee"].YValueMembers = "Kitoltvee";
			chart4.Series["Kitoltvee"].XValueMember = "Datum";
			chart4.Series["Kitoltvee"].ChartType = SeriesChartType.Column;
			chart4.Series["Kitoltvee"].LegendText = "IBC kitöltés";
			chart4.Series["Kitoltvee"].Color = Color.Orange;
			chart4.Series.Add("IBCkiurulte");
			chart4.Series["IBCkiurulte"].YValueMembers = "IBCkiurulte";
			chart4.Series["IBCkiurulte"].XValueMember = "Datum";
			chart4.Series["IBCkiurulte"].ChartType = SeriesChartType.Column;
			chart4.Series["IBCkiurulte"].LegendText = "IBC kiürülés";
			chart4.Series["IBCkiurulte"].Color = Color.Purple;
			chart4.Series.Add("Felrazvae");
			chart4.Series["Felrazvae"].YValueMembers = "Felrazvae";
			chart4.Series["Felrazvae"].XValueMember = "Datum";
			chart4.Series["Felrazvae"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvae"].LegendText = "Felrázás";
			chart4.Series["Felrazvae"].Color = Color.Blue;
			chart4.Series.Add("Felrazvahoe");
			chart4.Series["Felrazvahoe"].YValueMembers = "Felrazvahoe";
			chart4.Series["Felrazvahoe"].XValueMember = "Datum";
			chart4.Series["Felrazvahoe"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvahoe"].LegendText = "Folyadék hőmérséklet";
			chart4.Series["Felrazvahoe"].Color = Color.Green;
			chart4.Series.Add("Jerrycane");
			chart4.Series["Jerrycane"].YValueMembers = "Jerrycane";
			chart4.Series["Jerrycane"].XValueMember = "Datum";
			chart4.Series["Jerrycane"].ChartType = SeriesChartType.Column;							
			chart4.Series["Jerrycane"].Color = Color.Yellow;	
			chart4.Series["Jerrycane"].LegendText = "Jerrycane";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Urese");
			chart4.Series["Urese"].YValueMembers = "Urese";
			chart4.Series["Urese"].XValueMember = "Datum";
			chart4.Series["Urese"].ChartType = SeriesChartType.Column;							
			chart4.Series["Urese"].Color = Color.Brown;	
			chart4.Series["Urese"].LegendText = "Liquid tank üres";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Automatae");
			chart4.Series["Automatae"].YValueMembers = "Automatae";
			chart4.Series["Automatae"].XValueMember = "Datum";
			chart4.Series["Automatae"].ChartType = SeriesChartType.Column;							
			chart4.Series["Automatae"].Color = Color.RosyBrown;	
			chart4.Series["Automatae"].LegendText = "Automata hiba";			
			chart4.Series.Add("Szivarogepor");
			chart4.Series["Szivarogepor"].YValueMembers = "Szivarogepor";
			chart4.Series["Szivarogepor"].XValueMember = "Datum";
			chart4.Series["Szivarogepor"].ChartType = SeriesChartType.Column;
			chart4.Series["Szivarogepor"].LegendText = "Porszivárgás";
			chart4.Series["Szivarogepor"].Color = Color.DarkRed;
			chart4.Series.Add("Szivaroge");
			chart4.Series["Szivaroge"].YValueMembers = "Szivaroge";
			chart4.Series["Szivaroge"].XValueMember = "Datum";
			chart4.Series["Szivaroge"].ChartType = SeriesChartType.Column;							
			chart4.Series["Szivaroge"].Color = Color.DarkOliveGreen;	
			chart4.Series["Szivaroge"].LegendText = "Szivárgás";	
			chart4.Series.Add("Muszakie");
			chart4.Series["Muszakie"].YValueMembers = "Muszakie";
			chart4.Series["Muszakie"].XValueMember = "Datum";
			chart4.Series["Muszakie"].ChartType = SeriesChartType.Column;							
			chart4.Series["Muszakie"].Color = Color.Brown;	
			chart4.Series["Muszakie"].LegendText = "Műszaki hiba";	
			chart4.Series.Add("Idegene");
			chart4.Series["Idegene"].YValueMembers = "Idegene";
			chart4.Series["Idegene"].XValueMember = "Datum";
			chart4.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart4.Series["Idegene"].Color = Color.HotPink;	
			chart4.Series["Idegene"].LegendText = "Idegen anyag";			
			chart4.Series.Add("Komment");
			chart4.Series["Komment"].YValueMembers = "Komment";
			chart4.Series["Komment"].XValueMember = "Datum";
			chart4.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart4.Series["Komment"].Color = Color.Black;	
			chart4.Series["Komment"].LegendText = "Kommentezés";	
		}
		void Button18Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select * FROM nemmegpackeky WHERE Datum = ('" + comboBox2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart5.DataSource = ds.Tables[0];
			chart5.Titles.Add("Pack non komformitások");
			chart5.Series.Add("Tisztae");
			chart5.Series["Tisztae"].YValueMembers = "Tisztae";
			chart5.Series["Tisztae"].XValueMember = "Datum";
			chart5.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Tisztae"].LegendText = "Tisztaság";
			chart5.Series["Tisztae"].Color = Color.Red;
			chart5.Series.Add("POStisztae");
			chart5.Series["POStisztae"].YValueMembers = "POStisztae";
			chart5.Series["POStisztae"].XValueMember = "Datum";
			chart5.Series["POStisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["POStisztae"].LegendText = "POS tiszta";
			chart5.Series["POStisztae"].Color = Color.Orange;
			chart5.Series.Add("Kezitisztae");
			chart5.Series["Kezitisztae"].YValueMembers = "Kezitisztae";
			chart5.Series["Kezitisztae"].XValueMember = "Datum";
			chart5.Series["Kezitisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Kezitisztae"].LegendText = "Kézi tisztítás";
			chart5.Series["Kezitisztae"].Color = Color.Purple;
			chart5.Series.Add("Prepordere");
			chart5.Series["Prepordere"].YValueMembers = "Prepordere";
			chart5.Series["Prepordere"].XValueMember = "Datum";
			chart5.Series["Prepordere"].ChartType = SeriesChartType.Column;
			chart5.Series["Prepordere"].LegendText = "Preporder";
			chart5.Series["Prepordere"].Color = Color.Blue;
			chart5.Series.Add("Szitae");
			chart5.Series["Szitae"].YValueMembers = "Szitae";
			chart5.Series["Szitae"].XValueMember = "Datum";
			chart5.Series["Szitae"].ChartType = SeriesChartType.Column;
			chart5.Series["Szitae"].LegendText = "Szita";
			chart5.Series["Szitae"].Color = Color.Green;
			chart5.Series.Add("Szitaellazone");
			chart5.Series["Szitaellazone"].YValueMembers = "Szitaellazone";
			chart5.Series["Szitaellazone"].XValueMember = "Datum";
			chart5.Series["Szitaellazone"].ChartType = SeriesChartType.Column;							
			chart5.Series["Szitaellazone"].Color = Color.Yellow;	
			chart5.Series["Szitaellazone"].LegendText = "Szita azonos anyag";
			chart5.Series["Series1"].IsVisibleInLegend = false;	
			chart5.Series.Add("Serulese");
			chart5.Series["Serulese"].YValueMembers = "Serulese";
			chart5.Series["Serulese"].XValueMember = "Datum";
			chart5.Series["Serulese"].ChartType = SeriesChartType.Column;							
			chart5.Series["Serulese"].Color = Color.SaddleBrown;	
			chart5.Series["Serulese"].LegendText = "Bélészsák sérülés";	
			chart5.Series.Add("Beleszsake");
			chart5.Series["Beleszsake"].YValueMembers = "Beleszsake";
			chart5.Series["Beleszsake"].XValueMember = "Datum";
			chart5.Series["Beleszsake"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsake"].Color = Color.PaleGoldenrod;	
			chart5.Series["Beleszsake"].LegendText = "Bélészsák tiszta";			
			chart5.Series.Add("Szinhomogene");
			chart5.Series["Szinhomogene"].YValueMembers = "Szinhomogene";
			chart5.Series["Szinhomogene"].XValueMember = "Datum";
			chart5.Series["Szinhomogene"].ChartType = SeriesChartType.Column;
			chart5.Series["Szinhomogene"].LegendText = "Homogén szín";
			chart5.Series["Szinhomogene"].Color = Color.DarkRed;
			chart5.Series.Add("Beleszsakzare");
			chart5.Series["Beleszsakzare"].YValueMembers = "Beleszsakzare";
			chart5.Series["Beleszsakzare"].XValueMember = "Datum";
			chart5.Series["Beleszsakzare"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsakzare"].Color = Color.DarkOliveGreen;	
			chart5.Series["Beleszsakzare"].LegendText = "Bélészsák zár";	
			chart5.Series.Add("Packofffolye");
			chart5.Series["Packofffolye"].YValueMembers = "Packofffolye";
			chart5.Series["Packofffolye"].XValueMember = "Datum";
			chart5.Series["Packofffolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Packofffolye"].Color = Color.DarkSeaGreen;	
			chart5.Series["Packofffolye"].LegendText = "Pack off assign";	
			chart5.Series.Add("Idegene");
			chart5.Series["Idegene"].YValueMembers = "Idegene";
			chart5.Series["Idegene"].XValueMember = "Datum";
			chart5.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart5.Series["Idegene"].Color = Color.HotPink;	
			chart5.Series["Idegene"].LegendText = "Idegen anyag";	
			chart5.Series.Add("Vizfolye");
			chart5.Series["Vizfolye"].YValueMembers = "Vizfolye";
			chart5.Series["Vizfolye"].XValueMember = "Datum";
			chart5.Series["Vizfolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Vizfolye"].Color = Color.LimeGreen;	
			chart5.Series["Vizfolye"].LegendText = "Vízfolyás";			
			chart5.Series.Add("Komment");
			chart5.Series["Komment"].YValueMembers = "Komment";
			chart5.Series["Komment"].XValueMember = "Datum";
			chart5.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart5.Series["Komment"].Color = Color.Black;	
			chart5.Series["Komment"].LegendText = "Kommentezés";	
	
		}
		void DateTimePicker2ValueChanged(object sender, EventArgs e)
		{			
			Button19Click(null,null);
			Button20Click(null,null);
			Button21Click(null,null);
			Button22Click(null,null);
			Button23Click(null,null);	
			comboBox3.Enabled = false;
			comboBox1.Enabled = false;
			comboBox2.Enabled = false;		
			dateTimePicker2.Enabled = false;
		}
		void Button19Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select SUM(Kimerve) AS Kimerve, SUM(Felrazva) AS Felrazva, SUM(Felcimkezve) AS Felcimkezve, " +
	    	               "SUM(Uledeke) AS Uledeke, SUM(Idegene) AS Idegene,  SUM(Megfelelohoe) AS Megfelelohoe, SUM(Komment) AS Komment, ('" + dateTimePicker1.Text  + "-" + dateTimePicker2.Text +"') AS Datum from dbo.nemmegliqek WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart1.DataSource = ds.Tables[0];
			chart1.Titles.Add("Liquid non komformitások");
			chart1.Series.Add("Kimerve");
			chart1.Series["Kimerve"].YValueMembers = "Kimerve";
			chart1.Series["Kimerve"].XValueMember = "Datum";
			chart1.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart1.Series["Kimerve"].LegendText = "Kimérve";
			chart1.Series["Kimerve"].Color = Color.Red;
			chart1.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Felcimkezve");
			chart1.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart1.Series["Felcimkezve"].XValueMember = "Datum";
			chart1.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart1.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Uledeke");
			chart1.Series["Uledeke"].YValueMembers = "Uledeke";
			chart1.Series["Uledeke"].XValueMember = "Datum";
			chart1.Series["Uledeke"].ChartType = SeriesChartType.Column;
			chart1.Series["Uledeke"].LegendText = "Üledékes";
			chart1.Series["Uledeke"].Color = Color.Blue;
			chart1.Series["Uledeke"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Idegene");
			chart1.Series["Idegene"].YValueMembers = "Idegene";
			chart1.Series["Idegene"].XValueMember = "Datum";
			chart1.Series["Idegene"].ChartType = SeriesChartType.Column;
			chart1.Series["Idegene"].LegendText = "Idegen anyag";
			chart1.Series["Idegene"].Color = Color.Green;
			chart1.Series["Idegene"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Megfelelohoe");
			chart1.Series["Megfelelohoe"].YValueMembers = "Megfelelohoe";
			chart1.Series["Megfelelohoe"].XValueMember = "Datum";
			chart1.Series["Megfelelohoe"].ChartType = SeriesChartType.Column;							
			chart1.Series["Megfelelohoe"].Color = Color.Yellow;	
			chart1.Series["Megfelelohoe"].LegendText = "Megfelelő hő";
			chart1.Series["Series1"].IsVisibleInLegend = false;	
			chart1.Series["Megfelelohoe"]["PixelPointWidth"] = "100";
			chart1.Series.Add("Komment");
			chart1.Series["Komment"].YValueMembers = "Komment";
			chart1.Series["Komment"].XValueMember = "Datum";
			chart1.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart1.Series["Komment"].Color = Color.Black;	
			chart1.Series["Komment"].LegendText = "Kommentezés";	
			
		SqlDataAdapter da = new SqlDataAdapter("SELECT TOP (100) PERCENT Problem, SUM(Value) AS Value, MAX(DISTINCT Datum) AS Date FROM nemmegliqekpivot WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"') GROUP BY Problem ORDER BY Value DESC",@"Data Source=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
		DataSet das = new DataSet();
		da.Fill(das);
		dataGridView1.DataSource = das.Tables[0];
		}
		void Button20Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select SUM(Kimerve) AS Kimerve, SUM(Csomomentes) AS Csomomentes, SUM(Felcimkezve) AS Felcimkezve, " +
	    	               "SUM(Komment) AS Komment, ('" + dateTimePicker1.Text  + "-" + dateTimePicker2.Text +"') AS Datum from dbo.nemmegaklek WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart2.DataSource = ds.Tables[0];
			chart2.Titles.Add("Akl non komformitások");
			chart2.Series.Add("Kimerve");
			chart2.Series["Kimerve"].YValueMembers = "Kimerve";
			chart2.Series["Kimerve"].XValueMember = "Datum";
			chart2.Series["Kimerve"].ChartType = SeriesChartType.Column;
			chart2.Series["Kimerve"].LegendText = "Kimérve";
			chart2.Series["Kimerve"].Color = Color.Red;
			chart2.Series["Kimerve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Csomomentes");
			chart2.Series["Csomomentes"].YValueMembers = "Csomomentes";
			chart2.Series["Csomomentes"].XValueMember = "Datum";
			chart2.Series["Csomomentes"].ChartType = SeriesChartType.Column;
			chart2.Series["Csomomentes"].LegendText = "Csomós";
			chart2.Series["Csomomentes"].Color = Color.Orange;
			chart2.Series["Csomomentes"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Felcimkezve");
			chart2.Series["Felcimkezve"].YValueMembers = "Felcimkezve";
			chart2.Series["Felcimkezve"].XValueMember = "Datum";
			chart2.Series["Felcimkezve"].ChartType = SeriesChartType.Column;
			chart2.Series["Felcimkezve"].Color = Color.Pink;
			chart2.Series["Felcimkezve"].LegendText = "Idegen anyag";
			chart2.Series["Felcimkezve"]["PixelPointWidth"] = "100";
			chart2.Series.Add("Komment");
			chart2.Series["Komment"].YValueMembers = "Komment";
			chart2.Series["Komment"].XValueMember = "Datum";
			chart2.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart2.Series["Komment"].Color = Color.Black;	
			chart2.Series["Komment"].LegendText = "Kommentezés";	
			chart2.Series["Series1"].IsVisibleInLegend = false;	

		SqlDataAdapter da = new SqlDataAdapter("SELECT TOP (100) PERCENT Problem, SUM(Value) AS Value, MAX(DISTINCT Datum) AS Date FROM nemmegaklekpivot WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"') GROUP BY Problem ORDER BY Value DESC",@"Data Source=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
		DataSet das = new DataSet();
		da.Fill(das);
		dataGridView2.DataSource = das.Tables[0];
		}
		void Button21Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select SUM(IBCtisztae) AS IBCtisztae, SUM(Allomastisztae) AS Allomastisztae, SUM(Elese) AS Elese, SUM(Kimerteke) AS Kimerteke, " +
	    	               "SUM(Csomomentese) AS Csomomentese, SUM(Alapanyage) AS Alapanyage,  SUM(Bonthatoe) AS Bonthatoe, " +
	    	               "SUM(Idegene) AS Idegene, SUM(Komment) AS Komment, ('" + dateTimePicker1.Text  + "-" + dateTimePicker2.Text +"') AS Datum from dbo.nemmegbmpk WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart3.DataSource = ds.Tables[0];
			chart3.Titles.Add("Bmp non komformitások");
			chart3.Series.Add("IBCtisztae");
			chart3.Series["IBCtisztae"].YValueMembers = "IBCtisztae";
			chart3.Series["IBCtisztae"].XValueMember = "Datum";
			chart3.Series["IBCtisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["IBCtisztae"].LegendText = "IBC tiszta";
			chart3.Series["IBCtisztae"].Color = Color.Red;
			chart3.Series.Add("Allomastisztae");
			chart3.Series["Allomastisztae"].YValueMembers = "Allomastisztae";
			chart3.Series["Allomastisztae"].XValueMember = "Datum";
			chart3.Series["Allomastisztae"].ChartType = SeriesChartType.Column;
			chart3.Series["Allomastisztae"].LegendText = "Állomás tiszta";
			chart3.Series["Allomastisztae"].Color = Color.Orange;
			chart3.Series.Add("Elese");
			chart3.Series["Elese"].YValueMembers = "Elese";
			chart3.Series["Elese"].XValueMember = "Datum";
			chart3.Series["Elese"].ChartType = SeriesChartType.Column;
			chart3.Series["Elese"].LegendText = "Kés élese";
			chart3.Series["Elese"].Color = Color.Purple;
			chart3.Series.Add("Kimerteke");
			chart3.Series["Kimerteke"].YValueMembers = "Kimerteke";
			chart3.Series["Kimerteke"].XValueMember = "Datum";
			chart3.Series["Kimerteke"].ChartType = SeriesChartType.Column;
			chart3.Series["Kimerteke"].LegendText = "Kimérés";
			chart3.Series["Kimerteke"].Color = Color.Blue;
			chart3.Series.Add("Csomomentese");
			chart3.Series["Csomomentese"].YValueMembers = "Csomomentese";
			chart3.Series["Csomomentese"].XValueMember = "Datum";
			chart3.Series["Csomomentese"].ChartType = SeriesChartType.Column;
			chart3.Series["Csomomentese"].LegendText = "Csomós";
			chart3.Series["Csomomentese"].Color = Color.Green;
			chart3.Series.Add("Alapanyage");
			chart3.Series["Alapanyage"].YValueMembers = "Alapanyage";
			chart3.Series["Alapanyage"].XValueMember = "Datum";
			chart3.Series["Alapanyage"].ChartType = SeriesChartType.Column;							
			chart3.Series["Alapanyage"].Color = Color.Yellow;	
			chart3.Series["Alapanyage"].LegendText = "Alapanyag csomagolás";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Bonthatoe");
			chart3.Series["Bonthatoe"].YValueMembers = "Bonthatoe";
			chart3.Series["Bonthatoe"].XValueMember = "Datum";
			chart3.Series["Bonthatoe"].ChartType = SeriesChartType.Column;							
			chart3.Series["Bonthatoe"].Color = Color.Brown;	
			chart3.Series["Bonthatoe"].LegendText = "Alapanyag bontható";
			chart3.Series["Series1"].IsVisibleInLegend = false;	
			chart3.Series.Add("Idegene");
			chart3.Series["Idegene"].YValueMembers = "Idegene";
			chart3.Series["Idegene"].XValueMember = "Datum";
			chart3.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart3.Series["Idegene"].Color = Color.HotPink;	
			chart3.Series["Idegene"].LegendText = "Idegen anyag";
			chart3.Series.Add("Komment");
			chart3.Series["Komment"].YValueMembers = "Komment";
			chart3.Series["Komment"].XValueMember = "Datum";
			chart3.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart3.Series["Komment"].Color = Color.Black;	
			chart3.Series["Komment"].LegendText = "Kommentezés";	

		SqlDataAdapter da = new SqlDataAdapter("SELECT TOP (100) PERCENT Problem, SUM(Value) AS Value, MAX(DISTINCT Datum) AS Date FROM nemmegbmpkpivot WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"') GROUP BY Problem ORDER BY Value DESC",@"Data Source=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
		DataSet das = new DataSet();
		da.Fill(das);
		dataGridView3.DataSource = das.Tables[0];			

		}
		void Button22Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select SUM(Tisztae) AS Tisztae, SUM(Kitoltvee) AS Kitoltvee, SUM(IBCkiurulte) AS IBCkiurulte, SUM(Felrazvae) AS Felrazvae, " +
	    	               "SUM(Felrazvahoe) AS Felrazvahoe, SUM(Jerrycane) AS Jerrycane,  SUM(Urese) AS Urese, " +
	    	               "SUM(Automatae) AS Automatae, SUM(Szivarogepor) AS Szivarogepor, SUM(Szivaroge) AS Szivaroge, SUM(Muszakie) AS Muszakie, " +
						"SUM(Idegene) AS Idegene, SUM(Komment) AS Komment, ('" + dateTimePicker1.Text  + "-" + dateTimePicker2.Text +"') AS Datum " +
						"from dbo.nemmegblendek WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart4.DataSource = ds.Tables[0];
			chart4.Titles.Add("Blend non komformitások");
			chart4.Series.Add("Tisztae");
			chart4.Series["Tisztae"].YValueMembers = "Tisztae";
			chart4.Series["Tisztae"].XValueMember = "Datum";
			chart4.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart4.Series["Tisztae"].LegendText = "Tisztaság";
			chart4.Series["Tisztae"].Color = Color.Red;
			chart4.Series.Add("Kitoltvee");
			chart4.Series["Kitoltvee"].YValueMembers = "Kitoltvee";
			chart4.Series["Kitoltvee"].XValueMember = "Datum";
			chart4.Series["Kitoltvee"].ChartType = SeriesChartType.Column;
			chart4.Series["Kitoltvee"].LegendText = "IBC kitöltés";
			chart4.Series["Kitoltvee"].Color = Color.Orange;
			chart4.Series.Add("IBCkiurulte");
			chart4.Series["IBCkiurulte"].YValueMembers = "IBCkiurulte";
			chart4.Series["IBCkiurulte"].XValueMember = "Datum";
			chart4.Series["IBCkiurulte"].ChartType = SeriesChartType.Column;
			chart4.Series["IBCkiurulte"].LegendText = "IBC kiürülés";
			chart4.Series["IBCkiurulte"].Color = Color.Purple;
			chart4.Series.Add("Felrazvae");
			chart4.Series["Felrazvae"].YValueMembers = "Felrazvae";
			chart4.Series["Felrazvae"].XValueMember = "Datum";
			chart4.Series["Felrazvae"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvae"].LegendText = "Felrázás";
			chart4.Series["Felrazvae"].Color = Color.Blue;
			chart4.Series.Add("Felrazvahoe");
			chart4.Series["Felrazvahoe"].YValueMembers = "Felrazvahoe";
			chart4.Series["Felrazvahoe"].XValueMember = "Datum";
			chart4.Series["Felrazvahoe"].ChartType = SeriesChartType.Column;
			chart4.Series["Felrazvahoe"].LegendText = "Folyadék hőmérséklet";
			chart4.Series["Felrazvahoe"].Color = Color.Green;
			chart4.Series.Add("Jerrycane");
			chart4.Series["Jerrycane"].YValueMembers = "Jerrycane";
			chart4.Series["Jerrycane"].XValueMember = "Datum";
			chart4.Series["Jerrycane"].ChartType = SeriesChartType.Column;							
			chart4.Series["Jerrycane"].Color = Color.Yellow;	
			chart4.Series["Jerrycane"].LegendText = "Jerrycane";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Urese");
			chart4.Series["Urese"].YValueMembers = "Urese";
			chart4.Series["Urese"].XValueMember = "Datum";
			chart4.Series["Urese"].ChartType = SeriesChartType.Column;							
			chart4.Series["Urese"].Color = Color.Brown;	
			chart4.Series["Urese"].LegendText = "Liquid tank üres";
			chart4.Series["Series1"].IsVisibleInLegend = false;	
			chart4.Series.Add("Automatae");
			chart4.Series["Automatae"].YValueMembers = "Automatae";
			chart4.Series["Automatae"].XValueMember = "Datum";
			chart4.Series["Automatae"].ChartType = SeriesChartType.Column;							
			chart4.Series["Automatae"].Color = Color.RosyBrown;	
			chart4.Series["Automatae"].LegendText = "Automata hiba";			
			chart4.Series.Add("Szivarogepor");
			chart4.Series["Szivarogepor"].YValueMembers = "Szivarogepor";
			chart4.Series["Szivarogepor"].XValueMember = "Datum";
			chart4.Series["Szivarogepor"].ChartType = SeriesChartType.Column;
			chart4.Series["Szivarogepor"].LegendText = "Porszivárgás";
			chart4.Series["Szivarogepor"].Color = Color.DarkRed;
			chart4.Series.Add("Szivaroge");
			chart4.Series["Szivaroge"].YValueMembers = "Szivaroge";
			chart4.Series["Szivaroge"].XValueMember = "Datum";
			chart4.Series["Szivaroge"].ChartType = SeriesChartType.Column;							
			chart4.Series["Szivaroge"].Color = Color.DarkOliveGreen;	
			chart4.Series["Szivaroge"].LegendText = "Szivárgás";	
			chart4.Series.Add("Muszakie");
			chart4.Series["Muszakie"].YValueMembers = "Muszakie";
			chart4.Series["Muszakie"].XValueMember = "Datum";
			chart4.Series["Muszakie"].ChartType = SeriesChartType.Column;							
			chart4.Series["Muszakie"].Color = Color.Brown;	
			chart4.Series["Muszakie"].LegendText = "Műszaki hiba";	
			chart4.Series.Add("Idegene");
			chart4.Series["Idegene"].YValueMembers = "Idegene";
			chart4.Series["Idegene"].XValueMember = "Datum";
			chart4.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart4.Series["Idegene"].Color = Color.HotPink;	
			chart4.Series["Idegene"].LegendText = "Idegen anyag";			
			chart4.Series.Add("Komment");
			chart4.Series["Komment"].YValueMembers = "Komment";
			chart4.Series["Komment"].XValueMember = "Datum";
			chart4.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart4.Series["Komment"].Color = Color.Black;	
			chart4.Series["Komment"].LegendText = "Kommentezés";

		SqlDataAdapter da = new SqlDataAdapter("SELECT TOP (100) PERCENT Problem, SUM(Value) AS Value, MAX(DISTINCT Datum) AS Date FROM nemmegblendekpivot WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"') GROUP BY Problem ORDER BY Value DESC",@"Data Source=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
		DataSet das = new DataSet();
		da.Fill(das);
		dataGridView4.DataSource = das.Tables[0];	
			
		}
		void Button23Click(object sender, EventArgs e)
		{
			SqlConnection conn = new SqlConnection("server=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
			DataSet ds = new DataSet();	
			SqlDataAdapter dataAdapter1 = new SqlDataAdapter("select SUM(Tisztae) AS Tisztae, SUM(POStisztae) AS POStisztae, SUM(Kezitisztae) AS Kezitisztae, SUM(Prepordere) AS Prepordere, " +
	    	               "SUM(Szitae) AS Szitae, SUM(Szitaellazone) AS Szitaellazone, " +
	    	               "SUM(Serulese) AS Serulese, SUM(Beleszsake) AS Beleszsake, SUM(Szinhomogene) AS Szinhomogene," +
						"SUM(Beleszsakzare) AS Beleszsakzare, SUM(Packofffolye) AS Packofffolye, SUM(Idegene) AS Idegene, SUM(Vizfolye) AS Vizfolye,  " +
						"SUM(Komment) AS Komment, ('" + dateTimePicker1.Text  + "-" + dateTimePicker2.Text +"')  AS Datum from dbo.nemmegpackek WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"')", conn);
			dataAdapter1.Fill(ds);	
			chart5.DataSource = ds.Tables[0];
			chart5.Titles.Add("Pack non komformitások");
			chart5.Series.Add("Tisztae");
			chart5.Series["Tisztae"].YValueMembers = "Tisztae";
			chart5.Series["Tisztae"].XValueMember = "Datum";
			chart5.Series["Tisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Tisztae"].LegendText = "Tisztaság";
			chart5.Series["Tisztae"].Color = Color.Red;
			chart5.Series.Add("POStisztae");
			chart5.Series["POStisztae"].YValueMembers = "POStisztae";
			chart5.Series["POStisztae"].XValueMember = "Datum";
			chart5.Series["POStisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["POStisztae"].LegendText = "POS tiszta";
			chart5.Series["POStisztae"].Color = Color.Orange;
			chart5.Series.Add("Kezitisztae");
			chart5.Series["Kezitisztae"].YValueMembers = "Kezitisztae";
			chart5.Series["Kezitisztae"].XValueMember = "Datum";
			chart5.Series["Kezitisztae"].ChartType = SeriesChartType.Column;
			chart5.Series["Kezitisztae"].LegendText = "Kézi tisztítás";
			chart5.Series["Kezitisztae"].Color = Color.Purple;
			chart5.Series.Add("Prepordere");
			chart5.Series["Prepordere"].YValueMembers = "Prepordere";
			chart5.Series["Prepordere"].XValueMember = "Datum";
			chart5.Series["Prepordere"].ChartType = SeriesChartType.Column;
			chart5.Series["Prepordere"].LegendText = "Preporder";
			chart5.Series["Prepordere"].Color = Color.Blue;
			chart5.Series.Add("Szitae");
			chart5.Series["Szitae"].YValueMembers = "Szitae";
			chart5.Series["Szitae"].XValueMember = "Datum";
			chart5.Series["Szitae"].ChartType = SeriesChartType.Column;
			chart5.Series["Szitae"].LegendText = "Szita";
			chart5.Series["Szitae"].Color = Color.Green;
			chart5.Series.Add("Szitaellazone");
			chart5.Series["Szitaellazone"].YValueMembers = "Szitaellazone";
			chart5.Series["Szitaellazone"].XValueMember = "Datum";
			chart5.Series["Szitaellazone"].ChartType = SeriesChartType.Column;							
			chart5.Series["Szitaellazone"].Color = Color.Yellow;	
			chart5.Series["Szitaellazone"].LegendText = "Szita azonos anyag";
			chart5.Series["Series1"].IsVisibleInLegend = false;	
			chart5.Series.Add("Serulese");
			chart5.Series["Serulese"].YValueMembers = "Serulese";
			chart5.Series["Serulese"].XValueMember = "Datum";
			chart5.Series["Serulese"].ChartType = SeriesChartType.Column;							
			chart5.Series["Serulese"].Color = Color.Brown;	
			chart5.Series["Serulese"].LegendText = "Bélészsák sérülés";	
			chart5.Series.Add("Beleszsake");
			chart5.Series["Beleszsake"].YValueMembers = "Beleszsake";
			chart5.Series["Beleszsake"].XValueMember = "Datum";
			chart5.Series["Beleszsake"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsake"].Color = Color.RosyBrown;	
			chart5.Series["Beleszsake"].LegendText = "Bélészsák tiszta";			
			chart5.Series.Add("Szinhomogene");
			chart5.Series["Szinhomogene"].YValueMembers = "Szinhomogene";
			chart5.Series["Szinhomogene"].XValueMember = "Datum";
			chart5.Series["Szinhomogene"].ChartType = SeriesChartType.Column;
			chart5.Series["Szinhomogene"].LegendText = "Homogén szín";
			chart5.Series["Szinhomogene"].Color = Color.DarkRed;
			chart5.Series.Add("Beleszsakzare");
			chart5.Series["Beleszsakzare"].YValueMembers = "Beleszsakzare";
			chart5.Series["Beleszsakzare"].XValueMember = "Datum";
			chart5.Series["Beleszsakzare"].ChartType = SeriesChartType.Column;							
			chart5.Series["Beleszsakzare"].Color = Color.DarkOliveGreen;	
			chart5.Series["Beleszsakzare"].LegendText = "Bélészsák zár";	
			chart5.Series.Add("Packofffolye");
			chart5.Series["Packofffolye"].YValueMembers = "Packofffolye";
			chart5.Series["Packofffolye"].XValueMember = "Datum";
			chart5.Series["Packofffolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Packofffolye"].Color = Color.DarkSeaGreen;	
			chart5.Series["Packofffolye"].LegendText = "Pack off assign";	
			chart5.Series.Add("Idegene");
			chart5.Series["Idegene"].YValueMembers = "Idegene";
			chart5.Series["Idegene"].XValueMember = "Datum";
			chart5.Series["Idegene"].ChartType = SeriesChartType.Column;							
			chart5.Series["Idegene"].Color = Color.HotPink;	
			chart5.Series["Idegene"].LegendText = "Idegen anyag";	
			chart5.Series.Add("Vizfolye");
			chart5.Series["Vizfolye"].YValueMembers = "Vizfolye";
			chart5.Series["Vizfolye"].XValueMember = "Datum";
			chart5.Series["Vizfolye"].ChartType = SeriesChartType.Column;							
			chart5.Series["Vizfolye"].Color = Color.LimeGreen;	
			chart5.Series["Vizfolye"].LegendText = "Vízfolyás";			
			chart5.Series.Add("Komment");
			chart5.Series["Komment"].YValueMembers = "Komment";
			chart5.Series["Komment"].XValueMember = "Datum";
			chart5.Series["Komment"].ChartType = SeriesChartType.Line;							
			chart5.Series["Komment"].Color = Color.Black;	
			chart5.Series["Komment"].LegendText = "Kommentezés";	

		SqlDataAdapter da = new SqlDataAdapter("SELECT TOP (100) PERCENT Problem, SUM(Value) AS Value, MAX(DISTINCT Datum) AS Date FROM nemmegpackekpivot WHERE Datum BETWEEN ('" + dateTimePicker1.Text +"') AND ('" + dateTimePicker2.Text +"') GROUP BY Problem ORDER BY Value DESC",@"Data Source=gmacsm0001dp;database=Production_test;Integrated Security=SSPI");
		DataSet das = new DataSet();
		da.Fill(das);
		dataGridView5.DataSource = das.Tables[0];	

		}	
	}
}
